models/Recetas.py
from db.db import db

# class MateriaPrimaProveedor(db.Model):
#     __tablename__ = 'materia_prima_proveedor'
#     materiaprima_id = db.Column(db.Integer, db.ForeignKey('materiaprima.id'), primary_key=True)
#     proveedor_id = db.Column(db.Integer, db.ForeignKey('proveedor.id'), primary_key=True)

#     # Relación muchos a muchos con MateriaPrima
#     materiaprima = db.relationship('MateriaPrima', backref=db.backref('materia_prima_proveedor', lazy='dynamic'))
#     # Relación muchos a muchos con Proveedor
#     proveedor = db.relationship('Proveedor', backref=db.backref('materia_prima_proveedor', lazy='dynamic'))

class MateriaPrima(db.Model):
    __tablename__ = 'materiaprima'
    id = db.Column(db.Integer, primary_key=True)
    material = db.Column(db.String(255), nullable=False)
    tipo = db.Column(db.String(20), nullable=False)
    estatus = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, server_default=db.func.now(),default=db.func.now())
    updated_at = db.Column(db.DateTime, server_default=db.func.now(),default=db.func.now(), onupdate=db.func.now())
    deleted_at = db.Column(db.DateTime, nullable=True)
    

    def serialize(self):
        return {
            'id': self.id,
            'material': self.material,
            'tipo': self.tipo
        }

class Galletas(db.Model):
    __tablename__ = 'galletas'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(255), nullable=False)
    precio = db.Column(db.DECIMAL(10,2), nullable=False)
    enable = db.Column(db.Integer, default=1)
    descripcion = db.Column(db.Text)
    receta = db.Column(db.Text)
    totalGalletas = db.Column(db.Integer, default=0,nullable=False)
    pesoGalleta = db.Column(db.DECIMAL(10,2), nullable=False)
    created_at = db.Column(db.DateTime, server_default=db.func.now(),default=db.func.now())

    def serialize(self):
        return {
            'id': self.id,
            'nombre': self.nombre,
            'precio': self.precio,
            'enable': self.enable,
            'descripcion': self.descripcion,
            'receta': self.receta,
            'totalGalletas': self.totalGalletas,
            'pesoGalleta': self.pesoGalleta,
            'created_at': self.created_at
        }
    

class Ingredientes(db.Model):
    __tablename__ = 'ingredientes'
    id = db.Column(db.Integer, primary_key=True)
    galleta_id = db.Column(db.Integer, db.ForeignKey('galletas.id'), nullable=False)
    material_id = db.Column(db.Integer, db.ForeignKey('materiaprima.id'), nullable=False)
    cantidad = db.Column(db.DECIMAL(10,2), nullable=False)
    estatus = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, server_default=db.func.now(),default=db.func.now())
    updated_at = db.Column(db.DateTime, server_default=db.func.now(),default=db.func.now(), onupdate=db.func.now())
    deleted_at = db.Column(db.DateTime, nullable=True)
    
    # Relación muchos a uno con Galletas
    galletas = db.relationship('Galletas', backref=db.backref('ingredientes', lazy='dynamic'))

    def serialize(self):
        return {
            'id': self.id,
            'galleta_id': self.galleta_id,
            'material_id': self.material_id,
            'cantidad': self.cantidad,
            'estatus': self.estatus,
            'created_at': self.created_at,
            'updated_at': self.updated_at,
            'deleted_at': self.deleted_at
        }

routes/recetas.py
from flask import Blueprint, request, render_template,jsonify, Response,flash, redirect
from models.Recetas import Galletas,Ingredientes,MateriaPrima,db
from forms.Galleta import GalletaForm,Galleta2
from models.proveedor import Proveedor
from lib.d import D
from lib.jwt import allowed_roles, token_required
from lib.security import safe

from models.Inventario_galletas import Inventario_galletas


recetas = Blueprint('recetas', __name__, template_folder='templates')

log = D(debug=True)

# @recetas.route('/proveedores')
# def proveedores():
#     proveedores = Proveedor.query.all()
#     # prov = [proveedor.serialize() for proveedor in proveedores]
#     return Response("ok")


def get_Galletas():
    galletas = Galletas.query.filter_by(enable=1).all()
    return [galleta.serialize() for galleta in galletas]

def unused_materials(id):
    # Obtener todos los materiales con sus IDs
    all_materials = MateriaPrima.query.with_entities(MateriaPrima.material, MateriaPrima.id).all()

    # Obtener los IDs de los materiales que ya están en la receta
    used_materials = Ingredientes.query.filter_by(galleta_id=id).with_entities(Ingredientes.material_id).all()

    # Convertir los materiales utilizados en una lista de IDs
    used_material_ids = [material[0] for material in used_materials]

    # Filtrar los materiales que no están en la lista de usados
    unused_materials = [(material[0], material[1]) for material in all_materials if material[1] not in used_material_ids]

    # Retornar los nombres de los materiales no utilizados
    return [material[0] for material in unused_materials]


def get_names_materials(id):

    materiales = MateriaPrima.query.with_entities(MateriaPrima.material).all()


    return [material[0] for material in materiales]


def getIDbyName(name):
    material = MateriaPrima.query.filter_by(material=name).first()
    return material.id


def get_ingrediente(id):
    #unir las tablas de ingredientes y materia prima
    ingredientes = Ingredientes.query.filter_by(galleta_id=id).all()
    materiales = MateriaPrima.query.all()

    #crear un diccionario con los materiales
    materiales_dict = {}
    for material in materiales:
        materiales_dict[material.id] = material.serialize()

    #crear un diccionario con los ingredientes
    ingredientes_dict = {}
    for ingrediente in ingredientes:
        ingredientes_dict[ingrediente.id] = ingrediente.serialize()

    #unir los diccionarios
        
    for key in ingredientes_dict:
        ingredientes_dict[key]['material'] = materiales_dict[ingredientes_dict[key]['material_id']]['material']
        ingredientes_dict[key]['tipo'] = materiales_dict[ingredientes_dict[key]['material_id']]['tipo']

        ingredientes_dict[key].pop('material_id')

    return [ingrediente for ingrediente in ingredientes_dict.values()]



def get_galleta_by_id(id):
    galleta = Galletas.query.get(id)
    return galleta.serialize()



def get_tipo_material():
    material = MateriaPrima.query.with_entities(MateriaPrima.tipo).distinct().all()
    return [material[0] for material in material]

"""
ingredientes = [{'id': '5', 'cantidad': '500.00', 'tipo': 'gramos'}, {'id': '6', 'cantidad': '50.00', 'tipo': 'mililitros'}, {'id': '7', 'cantidad': '45.00', 'tipo': 'gramos'}, {'id': '8', 'cantidad': '100.00', 'tipo': 'gramos'}]
"""
def update_ingredientes(ingredientes):
    #hacer un bulk update
    for ingrediente in ingredientes:
        ingrediente_id = ingrediente['id']
        cantidad = ingrediente['cantidad']
        material = ingrediente['material']


        ingrediente = Ingredientes.query.get(ingrediente_id)
        ingrediente.cantidad = cantidad
        ingrediente.material_id = material
        db.session.commit()


def addIngrediente(galleta_id, material_id, cantidad):
    ingrediente = Ingredientes(galleta_id=galleta_id, material_id=material_id, cantidad=cantidad)
    db.session.add(ingrediente)
    db.session.commit()
        

def delete_galleta(id):
    #en lugar de eliminar la galleta, cambiar el estatus a 0
    galleta = Galletas.query.get(id)
    galleta.enable = 0
    db.session.commit()




def update_receta(id,receta,totalGalletas):
    galleta = Galletas.query.get(id)
    galleta.receta = receta
    galleta.totalGalletas = totalGalletas
    db.session.commit()

def controller_updates(form):
  
    # form regresa ImmutableMultiDict([('csrf_token', 'IjZjOTRjOGUyMTlhNTdkYzAzOGZmODJkNDlkNTRiNDFmYTdiZjU4M2Yi.ZgNnGA.-KwbwaZvAj06QHd7N-Wibb8QCFk'), ('tipo_5', 'gramos'), ('cantidad_5', '500.00'), ('material_5', 'avena'), ('tipo_6', 'mililitros'), ('cantidad_6', '50.00'), ('material_6', 'esencia de vainilla'), ('tipo_7', 'gramos'), ('cantidad_7', '5.00'), ('material_7', 'bicarbonato de sodio'), ('tipo_8', 'gramos'), ('cantidad_8', '100.00'), ('material_8', 'cacao en polvo'), ('receta', 'Galleta de chocolate con chips'), ('id', '2'), ('save', 'Guardar')])
    ingredientes = []
    materiales_agregados = set()  # Conjunto para mantener un registro de los materiales ya agregados

    for key in form:
        if 'cantidad_' in key:
            id = key.split('_')[1]
            material_nombre = form['material_'+id]
            cantidad = form['cantidad_'+id]
            material_id = getIDbyName(material_nombre)
            
            # Verificar si el material ya está en la lista de ingredientes
            if material_id in materiales_agregados:
                flash(f"No se puede agregar dos veces el material '{material_nombre}'.", 'warning')
                return False  # Retorna False si el material está duplicado
            #si la cantidad incluye letras, o es menor a 0, mandar un flash de error
            if not cantidad.replace('.','',1).isdigit() or float(cantidad) < 0:
                flash(f"La cantidad del material '{material_nombre}' no es válida.", 'warning')
                return False
            
            # Agregar el material a la lista de ingredientes y al conjunto de materiales agregados
            ingredientes.append({
                'id': id,
                'cantidad': cantidad,
                'material': getIDbyName(form['material_'+id])

            })
            materiales_agregados.add(material_id)  # Registrar el material en el conjunto

    log.warning(ingredientes)

    update_receta(form['id'], form['receta'], form['totalGalletas'])
    update_ingredientes(ingredientes)

    log.info(ingredientes)

def delete_ingredientes(id):
    ingrediente = Ingredientes.query.get(id)
    print(ingrediente)
    db.session.delete(ingrediente)

    db.session.commit()


@recetas.route('/recetas')
@token_required
@allowed_roles(['admin','produccion','compras','ventas'])
def index():
    recetas = get_Galletas()
    log.info(recetas)
    return render_template('pages/recetas/index.html', recetas=recetas)

@recetas.route('/recetas/<int:id>', methods=['GET', 'POST'])
@token_required
@allowed_roles(['admin','produccion','compras','ventas'])
def show(id):
    form = Galleta2(request.form)

    ingredientes = get_ingrediente(id)
    receta = get_galleta_by_id(id)
    receta = {key: receta[key] for key in ['id', 'receta', 'nombre', 'precio', 'descripcion', 'totalGalletas', 'pesoGalleta']}
    material_option = get_names_materials(id)
    tipo = get_tipo_material()
    form.totalGalletas.data = str(receta['totalGalletas'])
    print(f"ID: {id}")
    print(request.form)
    
    if request.method == 'POST':
        if 'delete' in request.form:
            delete_galleta(id)
            flash('Receta eliminada con éxito', 'success')
            return redirect('/recetas')
        if 'edit' in request.form:
            return render_template('pages/recetas/show.html', ingredientes=ingredientes, id=id, receta=receta, isEdit=True, material_options=material_option, tipos=tipo, form=form,unused_materials=unused_materials(id))
        elif 'regret' in request.form:
            return render_template('pages/recetas/show.html', ingredientes=ingredientes, id=id, receta=receta, isEdit=False,form=form)
        elif any([True for key in request.form if 'delete_' in key]):
            id_to_delete = [key.split('_')[1] for key in request.form if 'delete_' in key][0]
            delete_ingredientes(id_to_delete)
            # Después de eliminar, obtén la lista actualizada de ingredientes
            ingredientes = get_ingrediente(id)
            receta = get_galleta_by_id(id)
            return render_template('pages/recetas/show.html', ingredientes=ingredientes, id=id, receta=receta, isEdit=True,form=form, material_options=material_option, tipos=tipo,unused_materials=unused_materials(id))
        elif 'add' in request.form:
            material = safe(request.form['ingrediente'])
            cantidad = safe(request.form['cantidad'])
            
            update_receta(request.form['id'], request.form['receta'], request.form['totalGalletas'])
        

            addIngrediente(id, getIDbyName(material), cantidad)
            # Después de agregar, obtén la lista actualizada de ingredientes
            ingredientes = get_ingrediente(id)
            receta = get_galleta_by_id(id)
            form.totalGalletas.data = receta['totalGalletas']
            return render_template('pages/recetas/show.html', ingredientes=ingredientes, id=id, receta=receta, isEdit=True,form=form, material_options=material_option, tipos=tipo,unused_materials=unused_materials(id))
        elif 'save' in request.form:
            receta = safe(request.form['receta'])
            
            id = safe(request.form['id'])
            log.info(f"ID: {id}")
            
            try:
                controller_updates(request.form)
            except Exception as e:
                log.error(e)
            
            receta = get_galleta_by_id(id)
            form.totalGalletas.data = receta['totalGalletas']
            ingredientes = get_ingrediente(id)

templates/pages/recetas/create.html
{% extends 'layouts/layout_page.html' %} {% from 'macros/_button.html'
import Button %} {% from 'macros/_macros.html' import camposNuevos %}
{% block title %} Login - Cookies and Dreams{% endblock %} {% block
content %}

<style>
	.flash-messages {
		position: fixed;
		top: 0;
		left: 50%;
		transform: translateX(-50%);
		z-index: 1000;
		width: 100%;
		max-width: 600px;
		padding: 10px;
		color: #fff;
		text-align: center;
	}
	input[type='text'],
	input[type='email'],
	input[type='password'],
	input[type='number'],
	input[type='date'],
	input[type='time'],
	input[type='datetime-local'],
	select,
	textarea,
	input[type='search'] {
		background-color: white !important;
	}
</style>

<section class="w-full h-screen flex flex-col">
	<div class="flash-messages">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %} {% for category, message in messages %}
		<div class="alert alert-{{ category }}">{{ message }}</div>
		{% endfor %} {% endif %} {% endwith %}
	</div>

  <section class="grid grid-cols-1 md:grid-cols-2 overflow-x-hidden px-8 place-content-between mt-4">
		

		<!-- imagen -->
		<div class="flex justify-center">
			

				<figure>
				
								<img src=""
										 alt="galleta"
                     id="img2"
								/>
								
						
							
                <!-- boton para cambiar imagen -->
                <button class="btn btn-warning text-white" type="button" id="openDialog2" align="center">
                  Cambiar imagen
                </button>
					


				</figure>
		</div>

	
		<form method="POST" novalidate  class="card w-[600px] bg-secondary shadow-xl p-4 flex flex-col justify-between text-black" enctype="multipart/form-data">
			<dialog id="changeImage" class="modal" class="text-white">
				
				<div class="modal-box px-32 py-4">
					<h1>Cambiar imagen</h1>
				<img src=""
						 alt="galleta"
						 width="200"
						 height="200"
						 id="img"
						 class="my-4"
				/>
				<input type="file" name="file" id="file"
				class="file-input file-input-bordered w-full max-w-xs bg-white"  
				>

				
				<div class="modal-action" class="my-4">
					<input type="submit" name="change" value="Cambiar" class="btn btn-primary">
				<button
						type="button"
						id="closeDialog2"
						class="btn btn-error"
						>Cerrar</button>
				</div>
				</div>
			</dialog>
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
			
			
	
			<div>
					{% if not isEdit %}
							
							<h2
							class="text-pretty text-2xl font-bold text-center text-white"
							>Ingredientes</h2>
							<div class="w-full flex flex-col justify-center items-center my-4">
								<span class="text-pretty text-lg">
									<span class="text-white">
										Peso: 
									</span>
									{{ receta.pesoGalleta }} gramos
								</span>
								<span class="text-pretty text-lg">
									Porciones: {{ receta.totalGalletas }} galletas
								</span>
	
							</div>
							<ul>
									{% for ingrediente in ingredientes %}
											<li
											class="text-pretty text-lg "
											>{{ ingrediente.cantidad}} {{ ingrediente.tipo}} {{ ingrediente.material}}</li>
									{% endfor %}
							</ul>
							<p class="text-pretty text-lg my-4">{{ receta.receta }}</p>
							<input type="submit" name="edit" value="Editar" class="btn btn-primary">
							<a href="/recetas"
							class="btn btn-error"
							>Regresar</a>
							
					{% else %}
							<!-- Mostrar como tabla y text area -->
              <div>
								{{ camposNuevos(form.nombre) }}
               </div>
							 
              <div>
							 {{ camposNuevos(form.pesoGalleta) }}
              </div>

               <div>
								{{ camposNuevos(form.descripcion) }}
               </div>
               					
	
							<div class="flex justify-end space-x-4 my-4">
								<input type="submit" name="save" value="Guardar" class="btn btn-primary">
							<input type="submit" name="regret" value="Cancelar" class="btn btn-error text-white">
							
							</div>
						
					{% endif %}
			</div>
	</form>

	

	<script>
    const dialog = document.getElementById('addIngrediente');
    const dialog2 = document.getElementById('changeImage');
    const openDialog2 = document.getElementById('openDialog2');
    const closeDialog2 = document.getElementById('closeDialog2');
    const img = document.getElementById('img');
    const img2 = document.getElementById('img2');
    const fileInput = document.getElementById('file'); // Cambiado a fileInput para evitar la duplicación de nombres


		openDialog2.addEventListener('click', () => {
				dialog2.showModal();
		});
    
   
    closeDialog2.addEventListener('click', () => {
        dialog2.close();
        // Limpiar el input file
        fileInput.value = '';
        img.src = ''; // Limpiar la imagen
    });

    fileInput.addEventListener('change', () => {
        const file = fileInput.files[0]; // Obtener el primer archivo seleccionado
        if (file) {
            const reader = new FileReader();
            reader.onload = function(event) {
                img2.src = event.target.result;
                dialog2.close();
            };
            reader.readAsDataURL(file);
        }
    });
</script>

	
</section>


		<script>
			const flashMessage = document.querySelector('.flash-messages');
			if (flashMessage) {
				setTimeout(() => {
					flashMessage.remove();
				}, 5000);
			}
		</script>
	</section>
</section>
	{% endblock %}

templates/pages/recetas/index.html
{% extends 'layouts/layout_page.html' %} {% from 'macros/_button.html'
import Button %} {% from 'macros/_macros.html' import camposNuevos %}
{% block
content %}

<style>
	.flash-messages {
		position: fixed;
		top: 0;
		left: 50%;
		transform: translateX(-50%);
		z-index: 1000;
		width: 100%;
		max-width: 600px;
		padding: 10px;
		color: #fff;
		text-align: center;
	}
	input[type='text'],
	input[type='email'],
	input[type='password'],
	input[type='number'],
	input[type='date'],
	input[type='time'],
	input[type='datetime-local'],
	input[type='search'] {
		background-color: white;
	}
</style>

<section class="w-full h-screen flex flex-col">
	<div class="flash-messages">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %} {% for category, message in messages %}
		<div class="alert alert-{{ category }}">{{ message }}</div>
		{% endfor %} {% endif %} {% endwith %}
	</div>

	<div>
		<h1
        class="text-3xl font-bold text-primary mt-3 text-center">Recetas</h1>
		<div class="flex justify-center w-full">
			<a class="btn btn-primary mt-6 mb-3 w-52" href="{{url_for('recetas.create')}}">Crear Receta</a>
		</div>
	</div>
	<section
		class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4"
	>
	

		{% for receta in recetas %}
		<div class="card w-96 bg-secondary shadow-xl">
			<figure class="mt-3">
				<img
					src="{{ url_for('static', filename='img/' + receta.id|string + '.webp') }}"
					alt="{{ receta.nombre }}"
					width="100" class="mt-5"
				/>
			</figure>
			<div class="card-body">
				<h2 class="card-title">{{ receta.nombre }}</h2>
				<p class="text-gray-700">{{ receta.descripcion }}</p>
				<div class="card-actions justify-end">
					<a
					class="btn btn-primary mt-3"
					href={{url_for('recetas.show', id=receta.id)}}>Detalles</a>

				</div>
				
			</div>
		</div>
		{% endfor %}
	</section>

	<script>
		const flashMessage = document.querySelector('.flash-messages');
		if (flashMessage) {
			setTimeout(() => {
				flashMessage.remove();
			}, 5000);
		}
	</script>
</section>
{% endblock %}