models/compra.py
from db.db import db

class Compra(db.Model):
    __tablename__ = "compras"
    id = db.Column(db.Integer, primary_key=True)
    id_proveedor = db.Column(db.Integer, db.ForeignKey("proveedor.id"), nullable=False)
    id_usuario = db.Column(db.Integer, db.ForeignKey("usuario.id"), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    detalle_compra = db.relationship("DetalleCompra", backref="compra", lazy=True)
    
    def serialize(self):
        return {
            'id': self.id,
            'id_proveedor': self.id_proveedor,
            'id_usuario': self.id_usuario,
            'created_at': self.created_at
        }

forms/CompraForm.py
from flask_wtf import Form
from wtforms import StringField, IntegerField, TextAreaField, DateTimeField, SelectField
from wtforms.validators import DataRequired, Length


class CompraForm(Form):
    id_proveedor = SelectField(
        "Proveedor",
        choices=[
            ("", "Seleccione un proveedor"),
        ],
        validators=[DataRequired("El proveedor es requerido")],
        render_kw={
            "class": "select select-bordered select-primary w-full max-w-xs text-black"
        },
    )

    id_usuario = IntegerField("Usuario")

    created_at = DateTimeField("Fecha de creación")

routes/compras.py
from forms.CompraForm import CompraForm
from forms.DetalleCompraForm import DetalleCompraForm
from models.compra import Compra
from models.proveedor import Proveedor
from models.detalleCompra import DetalleCompra
from models.Recetas import MateriaPrima
from models.usuario import Usuario
from models.materia_prima_proveedor import MateriaPrimaProveedor
from models.inventario_mp import InventarioMP
from datetime import datetime
from db.db import db
from lib.security import safe
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    jsonify,
    Response,
)
from lib.jwt import (
    token_required,
    allowed_roles,
    createToken,
    decodeToken)

compras = Blueprint("compras", __name__, template_folder="templates")


@compras.route("/compras", methods=["GET", "POST"])
@token_required
@allowed_roles(roles=["admin", "compras"])
def index():
    active_token = request.cookies.get("token")
    token = decodeToken(active_token)
    email = token["email"]

    form = CompraForm()
    formDC = DetalleCompraForm(request.form)

    compras = Compra.query.all()
    det_com = DetalleCompra.query.all()
    proveedores = Proveedor.query.all()
    materias = MateriaPrima.query.all()
    mpp = MateriaPrimaProveedor.query.all()
    usuarios = Usuario.query.all()

    form.id_proveedor.choices = [
        (prov.id, prov.nombre_empresa)
        for prov in Proveedor.query.filter_by(estatus=1).all()
    ]

    compras_generales = []
    materias_primas_by_proveedor = []
    provs = []

    options = []
    mats = []

    for mp in mpp:
        for prov in proveedores:
            if mp.proveedor_id == prov.id:
                mat = MateriaPrima.query.filter_by(
                    id=mp.materiaprima_id).first()
                mats.append(
                    {
                        "id": mat.id,
                        "material": mat.material,
                        "presentacion": mp.tipo,
                        "precio": mp.precio,
                        "cantidad": mp.cantidad,
                        "medida": mp.tipo,
                    }
                )

                options.append(
                    {
                        "id_proveedor": prov.id,
                        "mats": mats,
                    }
                )

    for compra in compras:
        for det in det_com:
            if compra.id == det.id_compra:
                for prov in proveedores:
                    if compra.id_proveedor == prov.id:
                        for mat in materias:
                            if det.id_materia == mat.id:
                                for user in usuarios:
                                    if compra.id_usuario == user.id:
                                        compras_generales.append(
                                            {
                                                "id": compra.id,
                                                "proveedor": prov.nombre_empresa,
                                                "usuario": user.nombre,
                                                "material": mat.material,
                                                "cantidad": det.cantidad,
                                                "precio": det.precio_materia,
                                                "tipo": det.tipo,
                                                "fecha": compra.created_at,
                                            }
                                        )

    return render_template(
        "pages/compras/index.html",
        compras=compras_generales,
        cont=len(compras_generales),
        proveedores_list=proveedores,
        materias_list=materias_primas_by_proveedor,
        usuarios_list=usuarios,
        options=options,
        form=form,
    )


@compras.route("/purchase", methods=["POST"])
@token_required
@allowed_roles(roles=["admin", "compras"])
def purchase():
    active_token = request.cookies.get("token")
    token = decodeToken(active_token)
    email = token["email"]

    current_user = Usuario.query.filter_by(email=email).first()
    created_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        prov_id = request.form.get("slcProvider")

        compra = Compra(
            id_proveedor=prov_id,
            id_usuario=current_user.id,
            created_at=created_at,
        )

        db.session.add(compra)
        db.session.commit()

        mat_list = request.form.getlist("slcMateriaPrima[]")
        cantidad_list = request.form.getlist("txtCantidad[]")
        precio_list = request.form.getlist("txtPrecio[]")
        caduci_list = request.form.getlist("txtCaducidad[]")

        for ml, cl, pl, cad in zip(mat_list, cantidad_list, precio_list, caduci_list):
            presentacion = ml.split("-")[1]
            mat_id = ml.split("-")[0]

            det_compra = DetalleCompra(
                id_materia=safe(mat_id),
                precio_materia=safe(pl),
                cantidad=safe(cl),
                tipo=safe(presentacion),
                caducidad=safe(cad),
                id_compra=compra.id,
                created_at=created_at,
            )

            db.session.add(det_compra)
            db.session.commit()

            tipo = presentacion.split("_")[0]
            peso = presentacion.split("_")[1]
            medida = None

            if peso.find("kg") != -1:
                peso = peso.replace("kg", "")
                medida = (int(peso) * 1000) * int(cl)
            elif peso.find("ml") != -1:
                peso = peso.replace("ml", "")
                medida = (int(peso) * int(cl))
            elif peso.find("g") != -1:
                peso = peso.replace("g", "")
                medida = (int(peso) * int(cl))
            elif peso.find("lt") != -1:
                peso = int(peso) * 1000
                medida = (int(peso) * int(cl))

            inv_mpp = InventarioMP(
                id_materia_prima=mat_id,
                cantidad=medida,
                idCompra=compra.id,
                caducidad=cad,
                estatus=1,
                created_at=created_at,
            )

            db.session.add(inv_mpp)
            db.session.commit()

        flash("Compra realizada correctamente", "success")
        return redirect("/compras")
    except Exception as ex:
        print(ex)
        db.session.rollback()
        flash("Error al realizar la compra", "danger")
        return redirect("/compras")

templates/pages/compras/index.html
{% extends 'layouts/layout_page.html' %} {% from 'macros/_button.html'
import Button %} {% from 'macros/_compras.html' import lblipt,compra_field %}
{% block title %}Compras{% endblock %}
{% block content %}

<style>
    input[type='text'],
    input[type='email'],
    input[type='password'],
    input[type='number'],
    input[type='date'],
    input[type='time'],
    input[type='datetime-local'],
    select,
    input[type='search'] {
        background-color: white !important;
    }
</style>

<section class="w-full h-screen flex flex-col">
    <!-- Flash meesage -->
    <div class="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %} {% endif %} {% endwith %}
    </div>

    <h1
        class="text-3xl font-bold text-primary mt-3 text-center">Compras</h1>

    <!-- Button Add Purchase -->
    <div class="md:contaner px-4">
        <section class="mt-3">
            <button class="btn btn-primary float-end mx-3 text-white"
                id="btnAddPurchase">
                Agregar Compra
            </button>
            <button class="btn btn-info float-end text-white">
                <a href="{{url_for('inventario_mp.index')}}" class>
                    Inventario
                </a>
            </button>
        </section>
    </div>

    <!-- Table Compras -->
    <div class="md:contaner px-4">
        <section class="mt-5">
            <div class="relative overflow-x-auto">
                <table
                    class="w-full text-md text-left rtl:text-right text-black">
                    <thead
                        class="text-md uppercase bg-transparent text-center border-b-2 border-b-black">
                        <tr>
                            <th scope="col" class="px-6 py-3">Proveedor</th>
                            <th scope="col" class="px-6 py-3">Usuario</th>
                            <th scope="col" class="px-6 py-3">Materia Prima</th>
                            <th scope="col" class="px-6 py-3">Cantidad</th>
                            <th scope="col" class="px-6 py-3">Precio</th>
                            <th scope="col" class="px-6 py-3">Tipo</th>
                            <th scope="col" class="px-6 py-3">Fecha</th>
                        </tr>
                    </thead>
                    <tbody class="bg-transparent border-b text-center">
                        {% if cont > 0 %}
                        {% for compra in compras %}
                        <tr id="compra_{{compra.id}}">
                            <td class="border px-6 py-3">{{ compra.proveedor
                                }}</td>
                            <td class="border px-6 py-3">{{ compra.usuario
                                }}</td>
                            <td class="border px-6 py-3">{{ compra.material
                                }}</td>
                            <td class="border px-6 py-3">{{ compra.cantidad
                                }}</td>
                            <td class="border px-6 py-3">{{ compra.precio
                                }}</td>
                            <td class="border px-6 py-3">{{ compra.tipo }}</td>
                            <td class="border px-6 py-3">{{ compra.fecha }}</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>

    <!-- Dialog Add Purchase -->
    <form action="{{url_for('compras.purchase')}}" novalidate method="POST">
        <div class="card">
            <dialog id="addPurchase"
                class="dialog p-6 bg-base-100 shadow-lg rounded-md">
                <div class="dialog-title">
                    <h3 class="text-lg font-semibold">Agregar Compra</h3>
                </div>
                <div class="dialog-content">
                    <div class="grid grid-cols-2 gap-4 mb-4">
                        <input type="text" hidden name="csrf_token"
                            value="{{ csrf_token() }}" />
                        <div>
                            <div class="mt-3">
                                <label for="provider"
                                    class="text-gray-700">Proveedor</label>
                                <select
                                    class="select select-bordered select-primary min-w-full max-w-xs"
                                    name="slcProvider" id="slcProvider">
                                    <option value selected disabled>Seleccione
                                        un
                                        proveedor</option>
                                    {% for provider in proveedores_list %}
                                    <option class="text-black"
                                        value="{{ provider.id }}">{{
                                        provider.nombre_empresa
                                        }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="grid grid-cols-2 gap-4 mt-4"
                                id="btnsRow">
                                <div>
                                    <button type="button"
                                        class="btn btn-secondary w-auto"
                                        id="btnAddRow">
                                        Agregar otro insumo
                                    </button>
                                </div>
                                <div>
                                    <button type="button"
                                        class="btn btn-neutral w-auto"
                                        id="btnRemoveRow">
                                        Eliminar ultimo insumo
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div>
                            <div id="rowMatPrim">

                            </div>
                        </div>
                    </div>
                    <div class="flex justify-between mt-4">
                        <button type="submit" class="btn btn-warning w-52">
                            Solicitar
                        </button>
                        <button type="button"
                            class="btn btn-error w-48 text-white"
                            id="btnClosePurchase">
                            Cerrar
                        </button>
                    </div>
                </div>
            </dialog>
        </div>
    </form>
</section>

<!-- JavaScript Dialogs -->
<script>
    var options = {{ options | tojson }};
</script>
<script>
    const flashMessage = document.querySelector(".flash-messages");
    if (flashMessage) {
        setTimeout(() => {
            flashMessage.remove();
        }, 5000);
    }

    const btnAddPurchase = document.getElementById("btnAddPurchase");
    const addPurchase = document.getElementById("addPurchase");
    const btnClosePurchase = document.getElementById("btnClosePurchase");
    const slcProvider = document.getElementById("slcProvider");
    const rowMatPrim = document.getElementById("rowMatPrim");
    const slcMateriaPrima = document.getElementById("slcMateriaPrima");
    const btnsRow = document.getElementById("btnsRow");
    const btnAddRow = document.getElementById("btnAddRow");
    const btnRemoveRow = document.getElementById("btnRemoveRow");

    btnAddPurchase.addEventListener("click", () => {
        addPurchase.showModal();
        btnsRow.style.display = "none";
    });

    btnClosePurchase.addEventListener("click", () => {
        addPurchase.close();

        rowMatPrim.innerHTML = "";
    });

    slcProvider.addEventListener("change", function () {
        const selectedProveedorId = this.value;
        let optionsHTML = "<option value='' disabled selected>Seleccionar</option>";

        rowMatPrim.innerHTML = "";

        options.forEach((option) => {
            if (option.id_proveedor == selectedProveedorId) {
                var mats = option.mats;

                mats.forEach((mat) => {
                    optionsHTML += `<option value="${mat.id}-${mat.presentacion}">${mat.material} - ${mat.presentacion}</option>`;
                });
            }
        });

        const newRow = `
            <div class="mt-3">
                <div class="mt-1">
                    <label for="materia_prima">Materia Prima</label>
                    <select class="select select-bordered select-primary w-full max-w-xs text-black" name="slcMateriaPrima[]" id="slcMateriaPrima">
                        ${optionsHTML}
                    </select>
                </div>
                <div class="mt-1">
                    <label for="cantidad">Cantidad</label>
                    <input type="number" min="1" oninput="this.value = Math.abs(this.value)" class="input input-bordered input-primary w-full max-w-xs text-black" name="txtCantidad[]">
                </div>
                <div class="mt-1">
                    <label for="precio">Precio unitario</label>
                    <input type="number" min="1" oninput="this.value = Math.abs(this.value)" class="input input-bordered input-primary w-full max-w-xs text-black" name="txtPrecio[]">
                </div>
                <div class="mt-1">
                    <label for="fecha">Fecha de caducidad</label>
                    <input type="date" class="input input-bordered input-primary w-full max-w-xs text-black" name="txtCaducidad[]">
                </div>
            </div>`;


        rowMatPrim.innerHTML = newRow;

        btnsRow.style.display = "flex";

        const inputs = document.getElementsByTagName("input");

        for (var i = 0; i < inputs.length; i++) {
            inputs[i].addEventListener("keypress", function (event) {
                var inputType = this.type;
                var inputName = this.name;

                var charCode = event.keyCode || event.which;

                var charAllowed;

                if (inputName.includes("txtCantidad")){
                    charAllowed = /[1-9]/;
                }

                if (inputName.includes("txtPrecio")) {
                    charAllowed = /[1-9.]/;
                }

                if (!charAllowed.test(String.fromCharCode(charCode))) {
                    event.preventDefault();
                }
            });
        }

    });

    btnAddRow.addEventListener("click", () => {
        const selectedProveedorId = slcProvider.value;

        let optionsHTML = "<option value='' disabled selected>Seleccionar</option>";

        options.forEach((option) => {
            if (option.id_proveedor == selectedProveedorId) {
                var mats = option.mats;

                mats.forEach((mat) => {
                    optionsHTML += `<option value="${mat.id}-${mat.presentacion}">${mat.material} - ${mat.presentacion}</option>`;
                });
            }
        });

        const newRow = `
                <div class="mt-3">
                    <div class="mt-1">
                        <label for="materia_prima">Materia Prima</label>
                        <select class="select select-bordered select-primary w-full max-w-xs text-black" name="slcMateriaPrima[]" id="slcMateriaPrima">
                            ${optionsHTML}
                        </select>
                    </div>
                    <div class="mt-1">
                        <label for="cantidad">Cantidad</label>
                        <input type="number" min="1" oninput="this.value = Math.abs(this.value)" class="input input-bordered input-primary w-full max-w-xs text-black" name="txtCantidad[]">
                    </div>
                    <div class="mt-1">
                        <label for="precio">Precio unitario</label>
                        <input type="number" min="1" oninput="this.value = Math.abs(this.value)" class="input input-bordered input-primary w-full max-w-xs text-black" name="txtPrecio[]">
                    </div>
                    <div class="mt-1">
                        <label for="fecha">Fecha de caducidad</label>
                        <input type="date" class="input input-bordered input-primary w-full max-w-xs text-black" name="txtCaducidad[]">
                    </div>
                </div>`;

        rowMatPrim.insertAdjacentHTML("beforeend", newRow);


    });

    btnRemoveRow.addEventListener("click", () => {
        const rows = rowMatPrim.children;

        if (rows.length > 4) {
            rowMatPrim.removeChild(rows[rows.length - 1]);
            rowMatPrim.removeChild(rows[rows.length - 1]);
            rowMatPrim.removeChild(rows[rows.length - 1]);
            rowMatPrim.removeChild(rows[rows.length - 1]);
        }
    });
</script>
{% endblock %}