models/inventario_mp.py
from db.db import db
from sqlalchemy.orm import relationship

class InventarioMP(db.Model):
    __tablename__ = "inventario_mp"
    id = db.Column(db.Integer, primary_key=True)
    id_materia_prima = db.Column(db.Integer, db.ForeignKey('materiaprima.id'), nullable=False)
    cantidad = db.Column(db.String(200), nullable=False)
    idCompra = db.Column(db.Integer, db.ForeignKey('compras.id'), nullable=False)
    caducidad = db.Column(db.DateTime, nullable=False)
    estatus = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, nullable=False)
    
    def serialize(self):
        return {
            'id': self.id,
            'id_materia_prima': self.id_materia_prima,
            'cantidad': self.cantidad,
            'idCompra': self.idCompra,
            'caducidad': self.caducidad,
            'estatus': self.estatus,
            'created_at': self.created_at,
        }

forms/InventarioMP.py
from flask_wtf import Form
from wtforms import StringField, IntegerField, DateTimeField
from wtforms.validators import DataRequired, Length


class InventarioMPForm(Form):
    cantidad = IntegerField("Cantidad a comprar",
                            validators=[DataRequired(
                                message="La cantidad es requerida")],
                            render_kw={
                                "class": "input input-bordered input-primary w-full max-w-xs text-black"
                            })

    caducidad = DateTimeField("Fecha de caducidad")

    created_at = DateTimeField('Fecha de Creación')

routes/inventario_mp.py
from models.inventario_mp import InventarioMP
from models.compra import Compra
from models.detalleCompra import DetalleCompra
from models.Recetas import MateriaPrima
from models.proveedor import Proveedor
from models.materia_prima_proveedor import MateriaPrimaProveedor
from models.merma_materia import MermaMateria
from models.usuario import Usuario
from models.Produccion import Produccion
from db.db import db
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from lib.d import D
from lib.security import safe
from forms.InventarioMP import InventarioMPForm
from forms.MermaMateriaForm import MermaMateriaForm
from flask import Blueprint, render_template, request, flash, redirect
from lib.jwt import token_required, allowed_roles, createToken, decodeToken

log = D(debug=True)

inventario_mp = Blueprint("inventario_mp", __name__, template_folder="templates")


@inventario_mp.route("/inventario_mp", methods=["GET"])
@token_required
@allowed_roles(roles=["admin", "produccion"])
def index():
    active_token = request.cookies.get("token")
    token = decodeToken(active_token)
    email = token["email"]

    inv_mat_prima = InventarioMP.query.filter_by(estatus=1).all()
    materias_primas = MateriaPrima.query.all()
    compras = Compra.query.all()
    all_mermas = MermaMateria.query.all()

    log.info(f"hay una cantidad de merma de: {len(all_mermas)}")

    all_inv_mp = []
    all_merm = []
    fecha_actual = datetime.now()

    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formM = MermaMateriaForm()
    formM.merma_fecha.data = datetime.now()

    for merma in all_mermas:
        prov = Proveedor.query.filter_by(id=merma.id_proveedor).first()
        log.success(f"Proveedor: {prov}")
        log.error(f"idInventarioMaterias: {merma.serialize()}")

        mat = MateriaPrima.query.filter(
            MateriaPrima.id == merma.idInventarioMaterias
        ).first()
        log.success(f"Material: {mat}")

        if merma is None or mat is None:
            continue

        all_merm.append(
            {
                "id": merma.id,
                "idInventarioMaterias": merma.idInventarioMaterias,
                "merma_tipo": merma.merma_tipo,
                "merma_fecha": merma.merma_fecha,
                "cantidad": merma.cantidad,
                "created_at": merma.created_at,
                "id_produccion": merma.id_produccion,
                "id_proveedor": merma.id_proveedor,
                "justificacion": merma.justificacion,
                "nombre_empresa": prov.nombre_empresa,
                "material": mat.material,
            }
        )

    for inv_mp in inv_mat_prima:
        for mat in materias_primas:
            if inv_mp.id_materia_prima == mat.id:
                material = mat.material
                tipo = mat.tipo

                prov_mpp = MateriaPrimaProveedor.query.filter_by(
                    materiaprima_id=mat.id
                ).first()

                # if prov_mpp is None:
                #     continue

                prov = Proveedor.query.filter_by(id=prov_mpp.proveedor_id).first()
                merma_inv = MermaMateria.query.filter_by(
                    idInventarioMaterias=inv_mp.id
                ).first()

                estatus_merma = ""
                fecha_caducidad = inv_mp.caducidad

                if fecha_actual > inv_mp.caducidad:
                    merma = MermaMateria(
                        idInventarioMaterias=inv_mp.id,
                        merma_tipo="Caducidad",
                        merma_fecha=fecha,
                        cantidad=inv_mp.cantidad,
                        justificacion="Caducidad",
                        created_at=fecha,
                        id_produccion=None,
                        id_proveedor=int(prov.id),
                    )
                    
                    inv_mp.estatus = 0

                    db.session.add(merma)
                elif fecha_actual < inv_mp.caducidad:
                    inv_mp.estatus = 1
                    estatus_merma = "Consumible"

                estatus = ""
                db.session.commit()

                if int(inv_mp.cantidad) == 0:
                    estatus = "Agotado"
                elif int(inv_mp.cantidad) < 10 and int(inv_mp.cantidad) > 4:
                    estatus = "Por terminarse"
                elif int(inv_mp.cantidad) > 10:
                    estatus = "Disponible"

                nombre_empresa = (
                    Proveedor.query.filter_by(id=prov_mpp.proveedor_id)
                    .first()
                    .nombre_empresa
                )

                all_inv_mp.append(
                    {
                        "id": inv_mp.id,
                        "nombre": material,
                        "cantidad": inv_mp.cantidad,
                        "unidad_medida": tipo,
                        "proveedor": nombre_empresa,
                        "caducidad": str(fecha_caducidad).split(" ")[0],
                        "fecha_compra": inv_mp.created_at,
                        "estatus": estatus,
                        "merma": estatus_merma,
                    }
                )

    log.info(f"all_memas: {all_merm}")

    return render_template(
        "pages/inventario_mp/index.html",
        materia_primas=all_inv_mp,
        mermas=all_merm,
        formM=formM,
    )


@inventario_mp.route("/addmerma", methods=["POST"])
@token_required
@allowed_roles(roles=["admin", "produccion"])
def new_merma():
    active_token = request.cookies.get("token")
    token = decodeToken(active_token)
    email = token["email"]

    current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    form = MermaMateriaForm(request.form)

    try:
        id_inv_mat = request.form.get("id")
        merma_tipo = form.merma_tipo.data
        fecha_merma = form.merma_fecha.data
        cantidad_merma = form.cantidad.data
        justificacion_merma = form.justificacion.data

        imp = InventarioMP.query.filter_by(id=id_inv_mat, estatus=1).first()

        if imp is not None:
            if int(imp.cantidad) - int(cantidad_merma) > 0:

                compra = Compra.query.filter_by(id=imp.idCompra).first()
                proveedor = compra.id_proveedor

                merma = MermaMateria(
                    idInventarioMaterias=imp.id_materia_prima,
                    merma_tipo=safe(merma_tipo),
                    merma_fecha=safe(fecha_merma),
                    cantidad=safe(cantidad_merma),
                    justificacion=safe(justificacion_merma),
                    created_at=current_date,
                    id_produccion=None,
                    id_proveedor=int(proveedor),
                )
                log.info(f"Merma: {merma}")
                db.session.add(merma)

                imp.cantidad = int(imp.cantidad) - int(cantidad_merma)

                db.session.commit()

                log.info(f"Merma: {merma}")
                #imprimir todas las mermas
                all_mermas = MermaMateria.query.all()
                for merma in all_mermas:
                    log.info(f"Merma: {merma.serialize()}")

                flash("Se ha registrado la merma correctamente", "success")
            else:
                flash(
                    "La cantidad a mermar sobre pasa la cantidad total en inventario",
                    "error",
                )
        return redirect("/inventario_mp")
    except Exception as e:
        flash("Ocurrio un error al registrar la merma", "danger")
        db.session.rollback()
        log.error(e)
        return redirect("/inventario_mp")

templates/pages/inventario_mp/index.html
{% extends 'layouts/layout_page.html' %} {% from 'macros/_button.html'
import Button %} {% from 'macros/_inventario_mp.html' import addMerma,mermaField
%} {% block title %}Inventario de Materia Prima{% endblock %} {% block
content %}

<section class="w-full h-screen flex flex-col">
	<!-- Flash meesage -->
	<div class="flash-messages">
		{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %} {% for category, message in messages %}
		<div class="alert alert-{{ category }}">{{ message }}</div>
		{% endfor %} {% endif %} {% endwith %}
	</div>
	<div role="tablist" class="tabs tabs-bordered mt-5">
		<input type="radio" name="my_tabs_1" role="tab"
			class="tab text-lg text-primary" aria-label="Inventario" checked />
		<div role="tabpanel" class="tab-content">
			<h1
        class="text-3xl font-bold text-primary mt-3 text-center">Inventario</h1>
			<!-- Table Inventario -->
			<div class="md:contaner px-4">
				<section class="mt-5">
					<div class="relative overflow-x-auto">
						<table class="w-full text-sm text-left rtl:text-right text-black">
							<thead
								class="text-md uppercase bg-transparent text-center border-b-2 border-b-black">
								<tr>
									<th scope="col" class="px-6 py-3">Materia prima</th>
									<th scope="col" class="px-6 py-3">Cantidad</th>
									<th scope="col" class="px-6 py-3">
										Unidad de Medida
									</th>
									<th scope="col" class="px-6 py-3">Proveeedor</th>
									<th scope="col" class="px-6 py-3">Caducidad</th>
									<th scope="col" class="px-6 py-3">
										Fecha de compra
									</th>
									<th scope="col" class="px-6 py-3">Estatus</th>
									<th scope="col" class="px-6 py-3">Merma</th>
									<th scope="col" class="px-6 py-3">Acciones</th>
								</tr>
							</thead>
							<tbody class="bg-transparent border-b text-center text-md">
								{% for materia_prima in materia_primas %}
								<tr>
									<td class="px-6 py-3">
										{{ materia_prima.nombre }}
									</td>
									<td class="px-6 py-3">
										{{ materia_prima.cantidad }}
									</td>
									<td class="px-6 py-3">
										{{ materia_prima.unidad_medida }}
									</td>
									<td class="px-6 py-3">
										{{ materia_prima.proveedor }}
									</td>
									<td class="px-6 py-3">
										{{ materia_prima.caducidad }}
									</td>
									<td class="px-6 py-3">
										{{ materia_prima.fecha_compra }}
									</td>
									<td class="px-6 py-3">
										{{ materia_prima.estatus }}
									</td>
									<td class="px-6 py-3">{{ materia_prima.merma }}</td>
									<td class="px-6 py-3">
										<button class="btn btn-secondary" type="button"
											id="btnAddMerma_{{materia_prima.id}}">
											Mermar
										</button>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</section>
			</div>
		</div>

		<input type="radio" name="my_tabs_1" role="tab"
			class="tab text-lg text-primary" aria-label="Mermas" />
		<div role="tabpanel" class="tab-content">
			<h1
        class="text-3xl font-bold text-primary mt-3 text-center">Mermas</h1>
			<!-- Table Mermas -->
			<div class="md:container px-4">
				<section class="mt-5">
					<div class="relative overflow-x-auto">
						<table class="w-full text-md text-left rtl:text-right text-black"
							id="tbl_prov">
							<thead
								class="text-md uppercase bg-transparent text-center border-b-2 border-b-black">
								<tr>
									<th scope="col" class="px-6 py-3">Materia prima</th>
									<th scope="col" class="px-6 py-3">Causa merma</th>
									<th scope="col" class="px-6 py-3">
										Fecha de merma
									</th>
									<th scope="col" class="px-6 py-3">
										Cantidad mermada
									</th>
									<th scope="col" class="px-6 py-3">
										Justificaci&oacute;n
									</th>
									<th scope="col" class="px-6 py-3">Proveedor</th>
								</tr>
							</thead>
							<tbody class="bg-transparent border-b text-center text-md">
								{% for merma in mermas %}
								<tr>
									<td class="px-6 py-3">{{ merma.material }}</td>
									<td class="px-6 py-3">{{ merma.merma_tipo }}</td>
									<td class="px-6 py-3">{{ merma.merma_fecha }}</td>
									<td class="px-6 py-3">{{ merma.cantidad }}</td>
									<td class="px-6 py-3">{{ merma.justificacion }}</td>
									<td class="px-6 py-3">
										{{ merma.nombre_empresa }}
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</section>
			</div>
		</div>
	</div>

	<!-- Dialog Add Merma -->
	<form action="{{url_for('inventario_mp.new_merma')}}" novalidate method="POST">
		<div class="card">
			<dialog class="dialog p-6 bg-white shadow-lg rounded-md" id="addMerma">
				<div class="dialog-title">
					<h3 class="text-lg font-bold">Agregar merma</h3>
				</div>
				<div class="dialog-content">
					<input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
					<input type="hidden" name="id" id="id" />
					<div class="grid grid-cols-2 gap-4 mb-3 mt-3">
						<div>
							<div class="mt-3">
								{{ mermaField(formM.merma_tipo) }}
							</div>
							<div class="mt-3">
								{{ mermaField(formM.merma_fecha) }}
							</div>
							<div class="mt-3">
								{{ mermaField(formM.cantidad)
								}}
							</div>
						</div>
						<div>
							<div class="mt-3">
								{{ mermaField(formM.justificacion) }}
							</div>
						</div>
					</div>
					<div class="flex justify-end space-x-4 mt-4">
						<button type="submit" class="btn btn-warning">
							Agregar merma
						</button>
						<button type="button" class="btn btn-error text-white" id="btnCloseMerma">
							Cerrar
						</button>
					</div>
				</div>
			</dialog>
		</div>
	</form>
</section>

<!-- JavaScript -->
<script>
	const flashMessage = document.querySelector('.flash-messages');
	if (flashMessage) {
		setTimeout(() => {
			flashMessage.remove();
		}, 5000);
	}

	const current_date = new Date().toISOString().split('T')[0];
	const btnCloseMerma = document.getElementById('btnCloseMerma');
	const slcMerma = document.getElementById('slcMerma');
	const dialog = document.getElementById('addMerma');

	document.querySelectorAll('[id^="btnAddMerma_"]').forEach(button => {
		button.addEventListener('click', (e) => {
			const id = button.id.split("_")[1];
			document.querySelector("#id").value = id;
			dialog.showModal();
		});
	});

	btnCloseMerma.addEventListener('click', () => {
		dialog.close();
	});
</script>
{% endblock %}